name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Grants write access to the repository contents, including releases and assets

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Get version from tag
        id: get_version
        run: echo "::set-output name=version::${GITHUB_REF##*/}"

      - name: Build binary
        run: make build VERSION=${{ steps.get_version.outputs.version }}

      - name: Create GitHub Release   
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: ${{ steps.get_version.outputs.version }}
          files: ./notify_incident_io