name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Grants write access to repository contents, including releases and assets

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Get version from tag
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_ENV
  
      - name: Build binaries
        run: make release VERSION=${{ env.version }}
  

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          name: ${{ env.version }}
          files: ./notify_incident_io-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}